General overhaul and try for simplification.

diff --git a/check-host b/check-host
--- a/check-host
+++ b/check-host
@@ -1,20 +1,19 @@
-#!/bin/sh
+#!/bin/ksh
 #
 # check-host -- check if one or several hosts are alive and send status
-#               notifications.
+#               notifications
 #
-# Usage: check-host hostname
+# Usage: check-host
 #        check-host -f config-file
-#        check-host -t config-file
-#
-# Note: If called from crontab as a cronjob you would probably want to add
-#       "> /dev/null".
+#        check-host -n config-file
 #
 # Assumptions: The system is OpenBSD-stable or -current.
 #
 # Dependencies: cURL
 #
-# Copyright (c) 2015-2016, Joel A. Nilsson <joel@alikzus.se>
+# Last Changed: 2018-09-20 13:40:55 CEST
+#
+# Copyright (c) 2015-2018, Joel A. Hänel <joel@hanel.nu>
 #
 # Permission to use, copy, modify, and/or distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -34,16 +33,15 @@
 ################################################################################
 
 set -u
-trap "abort" HUP INT QUIT TERM
+trap "die" HUP INT QUIT TERM
 
 ################################################################################
-# DEFAULT CONFIGURATION
-# Should be set with a configuration file, e.g. ~/check-host.conf
+# CONFIGURATION
+# Should be set with a configuration file; the default is /etc/check-host.conf.
 ################################################################################
 
 MASTERS=""
 HOSTS=""
-
 PUSHOVER_TOKEN=""
 PUSHOVER_USER=""
 
@@ -51,203 +49,160 @@ PUSHOVER_USER=""
 # CONSTANTS
 ################################################################################
 
-NAME="check-host"
-CHECKPOINT="www.google.se"
-_HOST="$(/bin/hostname -s | perl -nle 'print "\u\L$_"')"
-_TMPDIR="/tmp/$NAME"
+NAME=${0##*/}
+CHECKPOINT="https://duckduckgo.com/?q=openbsd"
+MESSENGER="$(/bin/hostname -s | perl -nle 'print "\u\L$_"')"
 
 ################################################################################
 # SUBROUTINES
 ################################################################################
 
-abort() {
-    say "Aborted"
+# Source: https://apenwarr.ca/log/20110228
+echo() {
+    # remove this line if you don't want to support "-n"
+    [ "$1" = -n ] && { shift; FMT="%s"; } || FMT="%s\n"
+    printf "$FMT" "${*}"
+}
+
+die() {
+    echo "${*}"
     exit 1
-}
-
-error() {
-    fault "$1"
-    abort
-}
-
-fault() {
-    echo "!!! ${*}"
-}
-
-say() {
-    echo "==> ${*}"
 }
 
 usage() {
     echo
-    echo "Usage: $NAME [-ft] filename/host" >&2
+    echo "Usage: $NAME [-fn] filename" >&2
     echo
     echo "Options:"
-    echo "  -f    config file with hosts et cetera"
-    echo "  -t    send a test notification using a config file"
+    echo "  -f    config file"
+    echo "  -n    test configuration"
     echo
     exit 1
 }
 
-quit() {
-    say "$1"
-    exit 0
-}
-
 #===============================================================================
 
-check_connectivity() {
-    if [ ! -z "$CHECKPOINT" ]; then
-        ping_host "$CHECKPOINT" 3
-        if [ "$got_response" -eq 0 ]; then
-            quit "No connectivity; cannot proceed"
-        fi
-    else
-        error "No checkpoint was defined"
-    fi
-}
-
-# ping_host $hostname $number-of-tries 
-ping_host() {
-    tries=0
-    while [ $tries -lt "$2" ]; do
-        if /sbin/ping -c 1 -q "$1"; then
-            got_response=1
-            break
-        else
-            got_response=0
-        fi
-        tries=$((tries + 1))
-        sleep 1
-    done
-}
-
-poke_master() {
-    if [ ! -z "$MASTERS" ]; then
-        for master in $MASTERS; do
-            ping_host "$master" 10
-            if [ "$got_response" -eq 0 ]; then
-                say "The master is not responding"
-            else
-                quit "Nothing to be done"
-            fi
-        done
-    else
-        say "No master was defined"
-    fi
-}
-
-# notify $message
 notify() {
-    message="$1"
-
+    local title=$1
+    local message=$2
     curl -s \
         --form-string "token=$PUSHOVER_TOKEN" \
         --form-string "user=$PUSHOVER_USER" \
-        --form-string "title=$_HOST" \
+        --form-string "title=$title" \
         --form-string "message=$message" \
         https://api.pushover.net/1/messages.json \
         > /dev/null &
 }
 
-#===============================================================================
-
-check_response() {
-    cache="${_TMPDIR}/$1"
-    ping_host "$1" 60
-    if [ $got_response -eq 0 ]; then
-        no_response "$1"
-    else
-        response "$1"
-    fi
-}
-
-no_response() {
-    if [ -f "$cache" ]; then
-        count="$(cat "$cache")"
-
-        if [ "$count" -le 12 ]; then
-            time=60
-        elif [ "$count" -gt 12 ] && [ "$count" -le 18 ]; then
-            time=120
+ping_target() {
+    local target=$1
+    local trial=0
+    local limit=10
+    local pong
+    while [ "$trial" -lt "$limit" ]; do
+        if /sbin/ping -c 1 -q "$target" > /dev/null; then
+            pong=1
+            break
         else
-            time=720
+            pong=0
         fi
-
-        if [ "$(/usr/bin/find "$cache" -mmin +$time)" ]; then
-            count=$((count + 1))
-            echo "$count" > "$cache"
-            notify "$1 is still NOT responding to pings"
-        fi
-    else
-        echo "1" > "$cache"
-        notify "$1 is NOT responding to pings"
-    fi
-}
-
-response() {
-    if [ -f "$cache" ]; then
-        /bin/rm "$cache" | fault "Could NOT clear the cache"
-        notify "$1 has started to respond to pings again"
-    fi
+        trial=$((trial + 1))
+        sleep 1
+    done
+    return "$pong"
 }
 
 ################################################################################
 # MAIN
 ################################################################################
 
-if [ "$(/usr/bin/id -u)" -eq 0 ]; then
-    error "You should NOT run $NAME with root privileges"
-fi
+[ "$(/usr/bin/id -u)" -eq 0 ] && die "You cannot run $NAME with root privileges"
+[ -x "/usr/local/bin/curl" ]  || die "cURL is not installed"
 
-file_is_specified=0
-test_mode=0
-
-while getopts 'f:t' arg; do
+config_file=""
+test_config=0
+while getopts 'f:n' arg; do
     case $arg in
-    f)  file_is_specified=1 ;;
-    t)  test_mode=1 ;;
+    f)  config_file="$OPTARG";;
+    n)  test_config=1 ;;
     *)  usage ;;
     esac
 done
 
-if [ !  -d "$_TMPDIR" ]; then
-    /bin/mkdir "$_TMPDIR" || error "Could NOT create the temporary cache"
-fi
-
-check_connectivity
-
-if [ $file_is_specified -eq 1 ] || [ $test_mode -eq 1 ]; then
-    config_file="$2"
-
-    if [ -f "$config_file" ]; then
-        # shellcheck source=/dev/null
-        . "$config_file"
-    else
-        error "The config file $config_file does not exist"
-    fi
-
-    if [ $test_mode -eq 1 ]; then
-        notify "A trick from Nakor"
-        quit "Test done"
-    fi
-
-    poke_master
-
-    if [ ! -z "$HOSTS" ]; then
-        for host in $HOSTS; do
-            check_response "$host"
-        done
-    else
-        error "No hosts are defined"
-    fi
-elif [ $file_is_specified -eq 0 ] || [ $test_mode -eq 1 ]; then
-    error "A configuration file shall be defined for use with test mode"
+# Configuration
+[ -z "$config_file" ] && config_file="/etc/check-host.conf"
+if [ -f "$config_file" ]; then
+    # shellcheck source=/dev/null
+    . "$config_file"
 else
-    check_response "$1"
+    die "The configuration file $config_file does not exist"
 fi
 
-quit "Done"
+# Cache
+cache_dir="/tmp/$NAME"
+if [ -d "$cache_dir" ]; then
+    # Touch it so that daily(8) does not remove it.
+    /usr/bin/touch "$cache_dir"
+else
+    /bin/mkdir -p "$cache_dir" || die "Could NOT create the temporary cache"
+fi
 
-################################################################################
-# Last Changed: 2018-06-22 11:04:14 CEST
+# Internet connection?
+# Do not want to create a record if this host has no internet connection.
+if [ -n "$CHECKPOINT" ]; then
+    if ! /usr/bin/ftp -o - "${CHECKPOINT}" > /dev/null; then
+        die "No internet connection; cannot proceed"
+    fi
+else
+    die "No checkpoint was defined"
+fi
+
+# Test config?
+if [ $test_config -eq 1 ]; then
+    notify "A trick from Nakor"
+    exit 0
+fi
+
+# Master? 
+if [ -n "$MASTERS" ]; then
+    for master in $MASTERS; do
+        if ping_target "$master"; then
+            exit 0
+        fi
+    done
+fi
+
+# Checking
+[ -z "$HOSTS" ] && die "No hosts are defined"
+for target in $HOSTS; do
+    local cache="${cache_dir}/${target}"
+    if ping_target "$target"; then
+        local count
+        local minutes
+        if [ -f "$cache" ]; then
+            count="$(cat "$cache")"
+            if [ "$count" -le 6 ]; then
+                minutes=60
+            elif [ "$count" -gt 6 ] && [ "$count" -le 12 ]; then
+                minutes=120
+            else
+                minutes=720
+            fi
+            if [ "$(/usr/bin/find "$cache" -mmin +$minutes)" ]; then
+                count=$((count + 1))
+                echo "$count" > "$cache"
+                notify "${target}" "Still NOT responding to $MESSENGER"
+            fi
+        else
+            echo "1" > "$cache"
+            notify "${target}" "NOT responding to $MESSENGER"
+        fi
+    else
+        if [ -f "$cache" ]; then
+            /bin/rm "$cache"
+            notify "${target}" "Has responded to $MESSENGER"
+        fi
+    fi &
+done
+
+exit 0
